name: Create staging promotion pull request
on:
  push:
    branches:
      - develop
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d' date +%T)"
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Reset staging branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: staging-promotion
          body: ':crown: *** An automated PR initiated by: ${{github.actor}} ***'
          assignees: '${{github.actor}}'
          title: 'staging-promotion-${{ steps.date.outputs.date }}'
